package dto;

import exception.UnexpectedMessageTypeException;
import lombok.*;

/**
 * Rpc消息格式
 *
 * @author wangkaiping
 * @date 2023.4.26
 */
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
@Builder
@ToString
public class RpcMessage {

    /**
     * The version of rpc framework.
     */
    private byte version;
    /**
     * The message type of Rpc message, for example, Rpc request and Rpc response.
     */
    private byte messageType;
    /**
     * The serialization type.
     */
    private byte codec;
    /**
     * The compression type.
     */
    private byte compressType;
    /**
     * The identification of the request generated by UUID.
     */
    private int requestId;
    /**
     * The real Rpc request of response object.
     */
    private Object data;

}
